import java.util.List;

public class MccFactory {

    static final List<Mcc> mccs = List.of(
         new Mcc("0742", "Veterinary services"),
         new Mcc("0763", "Agricultural co-operatives"),
         new Mcc("0780", "Landscaping and horticultural services"),
         new Mcc("1520", "General contractors – residential & commercial"),
         new Mcc("1711", "Heating, plumbing, and air conditioning contractors"),
         new Mcc("1731", "Electrical contractors"),
         new Mcc("1740", "Masonry, stonework, tile setting, plastering & insulation contractors"),
         new Mcc("1750", "Carpentry contractors"),
         new Mcc("1761", "Roofing, siding, and sheet metal work contractors"),
         new Mcc("1771", "Asphalt, cement, and concrete work contractors"),
         new Mcc("1799", "Special trade contractors (not elsewhere classified)"),
         new Mcc("2741", "Miscellaneous publishing and printing"),
         new Mcc("2791", "Typesetting, plate making, and related services"),
         new Mcc("2842", "Specialty cleaning, polishing, & sanitation preparations"),
         new Mcc("4011", "Freight Railways"),
         new Mcc("4111", "Local passenger transportation"),
         new Mcc("4112", "Passenger railways"),
         new Mcc("4119", "Ambulance services"),
         new Mcc("4121", "Taxicabs and limousines"),
         new Mcc("4131", "Bus lines"),
         new Mcc("4214", "Motor freight carriers and trucking"),
         new Mcc("4215", "Courier services"),
         new Mcc("4225", "Public warehousing and storage"),
         new Mcc("4411", "Steamship and cruise lines"),
         new Mcc("4457", "Boat rentals and leasing"),
         new Mcc("4468", "Marinas, marine service, and supplies"),
         new Mcc("4511", "Airlines and air carriers (not elsewhere classified)"),
         new Mcc("4582", "Airports, flying fields, and airport terminals"),
         new Mcc("4722", "Travel agencies and tour operators"),
         new Mcc("4784", "Toll and bridge fees"),
         new Mcc("4789", "Transportation services (not elsewhere classified)"),
         new Mcc("4812", "Telecommunication equipment and telephone sales"),
         new Mcc("4813", "Key-entry telecom merchants"),
         new Mcc("4814", "Telecommunication services"),
         new Mcc("4816", "Computer network / information services"),
         new Mcc("4821", "Telegraph services"),
         new Mcc("4829", "Money transfer"),
         new Mcc("4899", "Cable, satellite, and other pay television and radio services"),
         new Mcc("4900", "Utilities – electric, gas, heating oil, sanitary, water"),
         new Mcc("5013", "Motor vehicle supplies and new parts"),
         new Mcc("5021", "Office and commercial furniture"),
         new Mcc("5039", "Construction materials (not elsewhere classified)"),
         new Mcc("5044", "Office, photographic, photocopy, and microfilm equipment"),
         new Mcc("5045", "Computers and computer peripheral equipment and services"),
         new Mcc("5046", "Commercial equipment (not elsewhere classified)"),
         new Mcc("5047", "Medical, dental, ophthalmic, and hospital equipment and supplies"),
         new Mcc("5051", "Metal service centers and offices"),
         new Mcc("5065", "Electrical parts and equipment"),
         new Mcc("5072", "Hardware equipment and supplies"),
         new Mcc("5074", "Plumbing and heating equipment and supplies"),
         new Mcc("5085", "Industrial supplies (not elsewhere classified)"),
         new Mcc("5094", "Precious stones, metals, watches, and jewelry"),
         new Mcc("5099", "Durable goods (not elsewhere classified)"),
         new Mcc("5111", "Stationery, office supplies, printing, and writing paper"),
         new Mcc("5122", "Drugs, drug proprietaries, and druggist sundries"),
         new Mcc("5131", "Piece goods, notions, and other dry goods"),
         new Mcc("5137", "Men's, women's, and children's uniforms, and commercial clothing"),
         new Mcc("5139", "Commercial footwear"),
         new Mcc("5169", "Chemicals and allied products (not elsewhere classified)"),
         new Mcc("5172", "Petroleum and petroleum products"),
         new Mcc("5192", "Books, periodicals, and newspapers"),
         new Mcc("5193", "Florist supplies, nursery stock, and flowers"),
         new Mcc("5198", "Paint, varnishes, and supplies"),
         new Mcc("5199", "Nondurable goods (not elsewhere classified)"),
         new Mcc("5200", "Home supply warehouse stores"),
         new Mcc("5211", "Lumber and building materials stores"),
         new Mcc("5231", "Glass, paint, and wallpaper stores"),
         new Mcc("5251", "Hardware stores"),
         new Mcc("5261", "Nurseries and lawn and garden supply stores"),
         new Mcc("5262", "Online marketplaces"),
         new Mcc("5271", "Mobile home dealers"),
         new Mcc("5300", "Wholesale clubs"),
         new Mcc("5309", "Duty free stores"),
         new Mcc("5310", "Discount stores"),
         new Mcc("5311", "Department stores"),
         new Mcc("5331", "Variety stores"),
         new Mcc("5399", "Miscellaneous general merchandise"),
         new Mcc("5411", "Grocery stores and supermarkets"),
         new Mcc("5422", "Freezer and locker meat provisioners"),
         new Mcc("5441", "Candy, nut, and confectionery stores"),
         new Mcc("5451", "Dairy products stores"),
         new Mcc("5462", "Bakeries"),
         new Mcc("5499", "Miscellaneous food stores – convenience stores and specialty markets"),
         new Mcc("5511", "Car and truck dealers (new and used) – sales, service, repairs, parts, and leasing"),
         new Mcc("5521", "Car and truck dealers (used only) – sales, service, repairs, parts, and leasing"),
         new Mcc("5531", "Auto and home supply stores"),
         new Mcc("5532", "Automotive tire stores"),
         new Mcc("5533", "Automotive parts and accessories stores"),
         new Mcc("5541", "Service stations"),
         new Mcc("5542", "Automated fuel dispensers"),
         new Mcc("5551", "Boat dealers"),
         new Mcc("5552", "Electric vehicle charging"),
         new Mcc("5561", "Camper, recreational, and utility trailer dealers"),
         new Mcc("5571", "Motorcycle shops and dealers"),
         new Mcc("5592", "Motor home dealers"),
         new Mcc("5598", "Snowmobile dealers"),
         new Mcc("5599", "Miscellaneous automotive, aircraft, and farm equipment dealers (not elsewhere classified)"),
         new Mcc("5611", "Men's and boys' clothing and accessories stores"),
         new Mcc("5621", "Women's ready-to-wear stores"),
         new Mcc("5631", "Women's accessory and specialty shops"),
         new Mcc("5641", "Children's and infants' wear stores"),
         new Mcc("5651", "Family clothing stores"),
         new Mcc("5655", "Sports and riding apparel stores"),
         new Mcc("5661", "Shoe stores"),
         new Mcc("5681", "Furriers and fur shops"),
         new Mcc("5691", "Men's and women's clothing stores"),
         new Mcc("5697", "Tailors, seamstresses, mending, and alterations"),
         new Mcc("5698", "Wig and toupee stores"),
         new Mcc("5699", "Miscellaneous apparel and accessory shops"),
         new Mcc("5712", "Furniture, home furnishings, and equipment stores, excepting appliances"),
         new Mcc("5713", "Floor covering stores"),
         new Mcc("5714", "Drapery, window covering, and upholstery stores"),
         new Mcc("5718", "Fireplace, fireplace screens, and accessories stores"),
         new Mcc("5719", "Miscellaneous home furnishing specialty stores"),
         new Mcc("5722", "Household appliance stores"),
         new Mcc("5732", "Electronics stores"),
         new Mcc("5733", "Music stores – musical instruments, pianos, and sheet music"),
         new Mcc("5734", "Computer software stores"),
         new Mcc("5735", "Record stores"),
         new Mcc("5811", "Caterers"),
         new Mcc("5812", "Eating places & restaurants"),
         new Mcc("5813", "Drinking places – bars, taverns, nightclubs, cocktail lounges, and discotheques"),
         new Mcc("5814", "Fast food restaurants"),
         new Mcc("5815", "Digital goods – books, movies, music, and NFTs"),
         new Mcc("5816", "Digital goods – games"),
         new Mcc("5817", "Digital goods – software applications (excluding games)"),
         new Mcc("5818", "Digital goods – multi-category"),
         new Mcc("5912", "Drug stores and pharmacies"),
         new Mcc("5921", "Package stores – beer, wine, and liquor"),
         new Mcc("5931", "Used merchandise and secondhand stores"),
         new Mcc("5932", "Antique shops – sales, repairs, and restoration services"),
         new Mcc("5933", "Pawn shops"),
         new Mcc("5935", "Wrecking and salvage yards"),
         new Mcc("5937", "Antique reproductions"),
         new Mcc("5940", "Bicycle shops – sales and service"),
         new Mcc("5941", "Sporting goods stores"),
         new Mcc("5942", "Book stores"),
         new Mcc("5943", "Stationery stores, office and school supply stores"),
         new Mcc("5944", "Jewelry stores, watches, clocks, and silverware stores"),
         new Mcc("5945", "Hobby, toy, and game shops"),
         new Mcc("5946", "Camera and photographic supply stores"),
         new Mcc("5947", "Gift, card, novelty, and souvenir shops"),
         new Mcc("5948", "Luggage and leather goods stores"),
         new Mcc("5949", "Sewing needlework, fabric, and piece goods stores"),
         new Mcc("5950", "Glassware / crystal stores"),
         new Mcc("5960", "Direct marketing – insurance services"),
         new Mcc("5963", "Door-to-door sales"),
         new Mcc("5964", "Direct marketing – catalog merchants"),
         new Mcc("5965", "Direct marketing – combination catalog and retail merchants"),
         new Mcc("5966", "Direct marketing – outbound telemarketing merchants (high-risk MCC)"),
         new Mcc("5967", "Direct marketing – inbound telemarketing merchants (high-risk MCC)"),
         new Mcc("5968", "Direct marketing – continuity/subscription merchants"),
         new Mcc("5969", "Direct marketing – other direct marketers (not elsewhere classified)"),
         new Mcc("5970", "Artists supply and craft shops"),
         new Mcc("5971", "Art dealers and galleries"),
         new Mcc("5972", "Stamp and coin stores"),
         new Mcc("5973", "Religious goods stores"),
         new Mcc("5975", "Hearing aids – sales, service, and supply"),
         new Mcc("5976", "Orthopedic goods – prosthetic devices"),
         new Mcc("5977", "Cosmetic stores"),
         new Mcc("5978", "Typewriters – sales, rentals, & service"),
         new Mcc("5983", "Fuel dealers – fuel oil, wood, coal, liquefied petroleum"),
         new Mcc("5992", "Florists"),
         new Mcc("5993", "Cigar stores and stands"),
         new Mcc("5994", "News dealers and newsstands"),
         new Mcc("5995", "Pet shops, pet foods and supplies stores"),
         new Mcc("5996", "Swimming pools – sales and service"),
         new Mcc("5997", "Electric razor stores"),
         new Mcc("5998", "Tent and awning shops"),
         new Mcc("5999", "Miscellaneous and specialty retail shops"),
         new Mcc("6010", "Financial institutions – manual cash disbursements"),
         new Mcc("6011", "Financial institutions – automated cash disbursements"),
         new Mcc("6012", "Financial institutions merchandise and services"),
         new Mcc("6050", "Quasi cash – customer financial institutions"),
         new Mcc("6051", "Non-financial institutions – foreign currency, money orders, and travelers cheques"),
         new Mcc("6211", "Security brokers / dealers"),
         new Mcc("6300", "Insurance sales, underwriting, and premiums"),
         new Mcc("6513", "Real estate agents and managers – rentals"),
         new Mcc("6532", "Payment transaction – customer financial institution"),
         new Mcc("6533", "Payment transaction – merchant"),
         new Mcc("6536", "MoneySend Intracountry"),
         new Mcc("6537", "MoneySend Intercountry"),
         new Mcc("6538", "MoneySend Funding"),
         new Mcc("6540", "POI Funding Transaction"),
         new Mcc("7011", "Lodging – hotels, motels, resorts, and central reservation services (not elsewhere classified)"),
         new Mcc("7012", "Timeshares"),
         new Mcc("7032", "Sporting and recreational camps"),
         new Mcc("7033", "Trailer parks and campgrounds"),
         new Mcc("7210", "Laundry, cleaning, and garment services"),
         new Mcc("7211", "Laundries – family and commercial"),
         new Mcc("7216", "Dry cleaners"),
         new Mcc("7217", "Carpet and upholstery cleaning"),
         new Mcc("7221", "Photographic studios"),
         new Mcc("7230", "Beauty and barber shops"),
         new Mcc("7251", "Shoe repair shops, shoe shine parlors, and hat cleaning shops"),
         new Mcc("7261", "Funeral service and crematories"),
         new Mcc("7273", "Dating services"),
         new Mcc("7276", "Tax preparation services"),
         new Mcc("7277", "Counseling services – debt, marriage, and personal"),
         new Mcc("7278", "Buying and shopping services and clubs"),
         new Mcc("7296", "Clothing rental – costumes, uniforms, and formal wear"),
         new Mcc("7297", "Massage parlors"),
         new Mcc("7298", "Health and beauty spas"),
         new Mcc("7299", "Miscellaneous personal services (not elsewhere classified)"),
         new Mcc("7311", "Advertising services"),
         new Mcc("7321", "Consumer credit reporting agencies"),
         new Mcc("7333", "Commercial photography, art, and graphics"),
         new Mcc("7338", "Quick copy, reproduction, and blueprinting services"),
         new Mcc("7339", "Stenographic and secretarial support"),
         new Mcc("7342", "Exterminating and disinfecting services"),
         new Mcc("7349", "Cleaning, maintenance, and janitorial services"),
         new Mcc("7361", "Employment agencies and temporary help services"),
         new Mcc("7372", "Computer programming, data processing, and integrated systems design services"),
         new Mcc("7375", "Information retrieval services"),
         new Mcc("7379", "Computer maintenance, repair, and services (not elsewhere classified)"),
         new Mcc("7392", "Management, consulting, and public relations services"),
         new Mcc("7393", "Detective agencies, protective services, and security services"),
         new Mcc("7394", "Equipment, tool, furniture, and appliance rental and leasing"),
         new Mcc("7395", "Photofinishing laboratories and photo developing"),
         new Mcc("7399", "Business services (not elsewhere classified)"),
         new Mcc("7512", "Automobile rental agency"),
         new Mcc("7513", "Truck and utility trailer rentals"),
         new Mcc("7519", "Motor home and recreational vehicle rentals"),
         new Mcc("7523", "Parking lots and garages"),
         new Mcc("7531", "Automotive body repair shops"),
         new Mcc("7534", "Tire retreading and repair shops"),
         new Mcc("7535", "Automotive paint shops"),
         new Mcc("7538", "Automotive service shops (non-dealer)"),
         new Mcc("7542", "Car washes"),
         new Mcc("7549", "Towing services"),
         new Mcc("7622", "Electronics repair shops"),
         new Mcc("7623", "Air conditioning and refrigeration repair shops"),
         new Mcc("7629", "Electrical and small appliance repair shops"),
         new Mcc("7631", "Watch, clock, and jewelry repair"),
         new Mcc("7641", "Furniture – reupholstery, repair, and refinishing"),
         new Mcc("7692", "Welding services"),
         new Mcc("7699", "Miscellaneous repair shops and related services"),
         new Mcc("7800", "Government-owned lotteries (US only)"),
         new Mcc("7801", "Internet gambling (US only)"),
         new Mcc("7802", "Government-licensed horse/dog racing (US only)"),
         new Mcc("7829", "Motion picture and video tape production and distribution"),
         new Mcc("7832", "Motion picture theaters"),
         new Mcc("7841", "Video tape rental stores"),
         new Mcc("7911", "Dance halls, studios, and schools"),
         new Mcc("7922", "Theatrical producers and ticket agencies"),
         new Mcc("7929", "Bands, orchestras, and miscellaneous entertainers (not elsewhere classified)"),
         new Mcc("7932", "Billiard and pool establishments"),
         new Mcc("7933", "Bowling alleys"),
         new Mcc("7941", "Commercial sports, professional sports clubs, athletic fields, and sports promoters"),
         new Mcc("7991", "Tourist attractions and exhibits"),
         new Mcc("7992", "Public golf courses"),
         new Mcc("7993", "Video amusement game supplies"),
         new Mcc("7994", "Video game arcades / establishments"),
         new Mcc("7995", "Betting, including lottery tickets, casino gaming chips, off-track betting, and wagers at race tracks"),
         new Mcc("7996", "Amusement parks, circuses, carnivals, and fortune tellers"),
         new Mcc("7997", "Membership clubs, country clubs, and private golf courses"),
         new Mcc("7998", "Aquariums, dolphinariums, zoos, and seaquariums"),
         new Mcc("7999", "Recreation services (not elsewhere classified)"),
         new Mcc("8011", "Doctors and physicians (not elsewhere classified)"),
         new Mcc("8021", "Dentists and orthodontists"),
         new Mcc("8031", "Osteopaths"),
         new Mcc("8041", "Chiropractors"),
         new Mcc("8042", "Optometrists and ophthalmologists"),
         new Mcc("8043", "Opticians, optical goods, and eyeglasses"),
         new Mcc("8049", "Podiatrists and chiropodists"),
         new Mcc("8050", "Nursing and personal care facilities"),
         new Mcc("8062", "Hospitals"),
         new Mcc("8071", "Medical and dental laboratories"),
         new Mcc("8099", "Medical services and health practitioners (not elsewhere classified)"),
         new Mcc("8111", "Legal services and attorneys"),
         new Mcc("8211", "Elementary and secondary schools"),
         new Mcc("8220", "Colleges, universities, professional schools, and junior colleges"),
         new Mcc("8241", "Correspondence schools"),
         new Mcc("8244", "Business and secretarial schools"),
         new Mcc("8249", "Vocational and trade schools"),
         new Mcc("8299", "Schools and educational services (not elsewhere classified)"),
         new Mcc("8351", "Child care services"),
         new Mcc("8398", "Charitable and social service organizations"),
         new Mcc("8641", "Civic, social, and fraternal associations"),
         new Mcc("8651", "Political organizations"),
         new Mcc("8661", "Religious organizations"),
         new Mcc("8675", "Automobile associations"),
         new Mcc("8699", "Membership organizations (not elsewhere classified)"),
         new Mcc("8734", "Testing laboratories (non-medical testing)"),
         new Mcc("8911", "Architectural, engineering, and surveying services"),
         new Mcc("8931", "Accounting, auditing, and bookkeeping services"),
         new Mcc("8999", "Professional sevices (not elsewhere classified)"),
         new Mcc("9211", "Court costs, including alimony and child support"),
         new Mcc("9222", "Fines"),
         new Mcc("9223", "Bail and bond payments"),
         new Mcc("9311", "Tax payments"),
         new Mcc("9399", "Government services (not elsewhere classified)"),
         new Mcc("9402", "Postal services – government only"),
         new Mcc("9405", "US federal government agencies or departments"),
         new Mcc("9406", "Government-owned lotteries (non-US)"),
         new Mcc("9950", "Intra-company purchases")
         );

    private MccFactory() {
        throw new IllegalStateException("MccFactory is static only class");
    }

    public static List<Mcc> getMccList() {
        return mccs;
    }
}
